### ISSUE TITLE
Doesn’t work on GNOME 44

### ISSUE THREAD

**Issue by ai** [LynithDev/gnome-app-hider#2]
I tried on Fedora 38. I see `Hide` item in the menu, but clicking on it doesn’t hide the icon (but the hidden app appears in extension settings).

**Comment by LynithDev** [comment]
Hm that's strange. I'll attempt to fix it when I have time as well as another issue I found earlier today. I'll let you know when I've fixed it

**Comment by LynithDev** [comment]
Hey again. I ran a live install of Fedora 38 beta to try out GNOME 44 and try recreate the issue. Though the extension works fine.

**Potential fix 1**
Can you make sure you're running the latest version (3) of the extension first.

**Otherwise...**
Could you open a terminal, and run the following command for me:
```
journalctl -f -o cat /usr/bin/gnome-shell
```
After that, re-enable the extension and look at try hiding an app icon. If you see anything in the terminal that references the extension, please copy and paste the text here so I can attempt to fix the issue

**Comment by ai** [comment]
I found the reason of bug: it is a conflict with [Alphabetical App Grid](https://extensions.gnome.org/extension/4269/alphabetical-app-grid/)

**Comment by LynithDev** [comment]
Looking at the extensions source, it does indeed cause an incompatibility. I'll try my best to make it compatible nevertheless. Thanks for the report

**Comment by LynithDev** [comment]
Well, I uploaded a [fix](https://github.com/LynithDev/gnome-app-hider/releases/tag/4) for your issue. However I can't seem to fix 2 things:
1. Alphabetical Grid Order sometimes causes the icons to not animate / reload the app display properly
2. Alphabetical Grid Order will **not** reload the folder view when you hide an app (You can just exit the folder view and go back in and the icon should be hidden)

**Comment by ai** [comment]
Thanks a lot! Works as charm
